apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - k8s/configmap-openclaw.yaml
  - k8s/deployment-openclaw.yaml
  #- k8s/deployment-runner.yaml
  - k8s/service-openclaw.yaml
  - k8s/service-runner.yaml
  #- k8s/resourcequota-openclaw.yaml
  - k8s/virtualservice-openclaw.yaml
  - k8s/clusterrolebinding-openclaw.yaml
  #- k8s/pdb-openclaw.yaml
  - k8s/hpa-openclaw.yaml
  - k8s/networkpolicy-openclaw.yaml

# NOTA: El namespace lo crea ArgoCD via CreateNamespace=true
# Los Secrets y runner-kubeconfig se manejan fuera de Git
