apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"istio-injection":"enabled"},"name":"openclaw"}}
  creationTimestamp: "2026-05-18T20:35:36Z"
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: openclaw
  name: openclaw
  resourceVersion: "21796962"
  uid: 5c32cd82-8fa6-4627-86ba-a0dd62f804b0
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
