apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
  name: openclaw-quota
  namespace: openclaw
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "5"
    requests.cpu: "2"
    requests.memory: 4Gi
status:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "5"
    requests.cpu: "2"
    requests.memory: 4Gi
  used:
    limits.cpu: 2500m
    limits.memory: 4Gi
    pods: "2"
    requests.cpu: 600m
    requests.memory: 1280Mi
