apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-05-18T20:35:36Z"
    name: default
    namespace: openclaw
    resourceVersion: "21794512"
    uid: bf1314c5-4f25-446b-bcdc-f1384995de67
kind: List
metadata:
  resourceVersion: ""
